
# This file is used to configure the Supabase project

project_id = "ltzrdfiqivmedupzcndj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.parse-resume]
