
import { Internship } from '@/types/internships';

/**
 * Mock internship data for demonstration purposes
 */
export const mockInternships: Internship[] = [
  {
    id: "INT001",
    title: "Software Engineering Intern",
    description: "Join our engineering team to work on cutting-edge software solutions. You'll gain hands-on experience with our core product development, participate in code reviews, and learn from senior developers.",
    company: "Emirates Digital Technologies",
    location: "Dubai Internet City, Dubai, UAE",
    start_date: "2025-06-01",
    end_date: "2025-09-01",
    application_deadline: "2025-05-15",
    is_paid: true,
    stipend_amount: 4500,
    currency: "AED",
    requirements: [
      "Currently pursuing a Bachelor's degree in Computer Science or related field",
      "Knowledge of at least one programming language (JavaScript, Python, Java)",
      "Strong problem-solving skills"
    ],
    skills_required: ["JavaScript", "React", "Git", "API Integration"],
    industry: "Information Technology",
    department: "Software Development",
    education_level: "Undergraduate",
    contact_email: "careers@emiratestech.ae",
    website_url: "https://emiratestech.ae/careers",
    is_active: true,
    created_at: "2025-04-01",
    created_by: "user-123"
  },
  {
    id: "INT002",
    title: "Marketing Intern",
    description: "Support our marketing team in developing and implementing marketing strategies for local and international clients. You'll assist with social media campaigns, content creation, and market research.",
    company: "Dubai Media Group",
    location: "Dubai Media City, Dubai, UAE",
    start_date: "2025-07-01",
    end_date: "2025-12-31",
    application_deadline: "2025-06-15",
    is_paid: true,
    stipend_amount: 3800,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Marketing, Communications, or related field",
      "Excellent written and verbal communication skills",
      "Familiarity with social media platforms"
    ],
    skills_required: ["Social Media Marketing", "Content Creation", "Market Research", "Analytics"],
    industry: "Media & Communications",
    department: "Marketing",
    education_level: "Undergraduate",
    contact_email: "internships@dubaimediagroup.ae",
    website_url: "https://dubaimediagroup.ae",
    is_active: true,
    created_at: "2025-04-05",
    created_by: "user-456"
  },
  {
    id: "INT003",
    title: "Finance Analyst Intern",
    description: "Work alongside our finance team to analyze financial data, prepare reports, and assist with budgeting processes. This internship offers exposure to financial planning and analysis in a fast-paced environment.",
    company: "Emirates Investment Bank",
    location: "Dubai International Financial Centre, Dubai, UAE",
    start_date: "2025-06-15",
    end_date: "2025-09-15",
    application_deadline: "2025-05-30",
    is_paid: true,
    stipend_amount: 5000,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Finance, Accounting, or Economics",
      "Strong analytical skills",
      "Proficiency in Excel and financial modeling"
    ],
    skills_required: ["Financial Analysis", "Excel", "Data Visualization", "Financial Modeling"],
    industry: "Banking & Finance",
    department: "Financial Analysis",
    education_level: "Undergraduate",
    contact_email: "careers@emiratesinvestment.ae",
    website_url: "https://emiratesinvestment.ae",
    is_active: true,
    created_at: "2025-03-28",
    created_by: "user-789"
  },
  {
    id: "INT004",
    title: "Architectural Design Intern",
    description: "Join one of Dubai's premier architectural firms and contribute to ongoing residential and commercial projects. You'll work with experienced architects on design concepts, 3D modeling, and client presentations.",
    company: "Dubai Design Associates",
    location: "Business Bay, Dubai, UAE",
    start_date: "2025-09-01",
    end_date: "2026-03-01",
    application_deadline: "2025-07-31",
    is_paid: true,
    stipend_amount: 4200,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Architecture or related design field",
      "Proficiency in CAD software and 3D modeling",
      "Strong design portfolio"
    ],
    skills_required: ["AutoCAD", "Revit", "SketchUp", "3D Visualization", "Design Thinking"],
    industry: "Architecture & Design",
    department: "Design Studio",
    education_level: "Undergraduate",
    contact_email: "hr@dubaidesign.ae",
    website_url: "https://dubaidesign.ae",
    is_active: true,
    created_at: "2025-04-10",
    created_by: "user-101"
  },
  {
    id: "INT005",
    title: "Data Science Intern",
    description: "An exciting opportunity to work with our data science team on real-world data analytics projects. You'll help collect and process data, apply machine learning algorithms, and communicate insights to stakeholders.",
    company: "Smart Dubai Analytics",
    location: "Dubai Silicon Oasis, Dubai, UAE",
    start_date: "2025-07-15",
    end_date: "2025-10-15",
    application_deadline: "2025-06-15",
    is_paid: true,
    stipend_amount: 4800,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Data Science, Statistics, Computer Science, or related field",
      "Experience with Python and data analysis libraries",
      "Understanding of machine learning concepts"
    ],
    skills_required: ["Python", "SQL", "Machine Learning", "Data Visualization", "Statistical Analysis"],
    industry: "Information Technology",
    department: "Data Science",
    education_level: "Graduate",
    contact_email: "careers@smartdubai.ae",
    website_url: "https://smartdubai.ae",
    is_active: true,
    created_at: "2025-03-20",
    created_by: "user-202"
  },
  {
    id: "INT006",
    title: "Human Resources Intern",
    description: "Support our HR team in various aspects of human resource management including recruitment, onboarding, employee relations, and HR administration. Gain practical experience in a dynamic corporate environment.",
    company: "Emirates Group",
    location: "Sheikh Zayed Road, Dubai, UAE",
    start_date: "2025-06-01",
    end_date: "2025-08-31",
    application_deadline: "2025-05-01",
    is_paid: true,
    stipend_amount: 3500,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Human Resources, Business Administration, or related field",
      "Strong interpersonal and communication skills",
      "Knowledge of HR principles and practices"
    ],
    skills_required: ["Recruitment", "HRIS", "Employee Relations", "Organization"],
    industry: "Human Resources",
    department: "HR",
    education_level: "Undergraduate",
    contact_email: "hr@emiratesgroup.ae",
    website_url: "https://emiratesgroup.ae/careers",
    is_active: true,
    created_at: "2025-04-02",
    created_by: "user-303"
  },
  {
    id: "INT007",
    title: "Mechanical Engineering Intern",
    description: "Join our engineering team working on innovative mechanical systems for construction and infrastructure projects. You'll assist in design, testing, and documentation of mechanical components.",
    company: "Dubai Engineering Solutions",
    location: "Jebel Ali, Dubai, UAE",
    start_date: "2025-08-15",
    end_date: "2026-02-15",
    application_deadline: "2025-07-15",
    is_paid: true,
    stipend_amount: 5200,
    currency: "AED",
    requirements: [
      "Pursuing a Bachelor's degree in Mechanical Engineering",
      "Knowledge of CAD software",
      "Understanding of mechanical principles and materials"
    ],
    skills_required: ["AutoCAD", "SolidWorks", "Mechanical Design", "Technical Documentation"],
    industry: "Engineering",
    department: "Mechanical Engineering",
    education_level: "Undergraduate",
    contact_email: "careers@dubaiengsolutions.ae",
    website_url: "https://dubaiengsolutions.ae",
    is_active: true,
    created_at: "2025-04-15",
    created_by: "user-404"
  },
  {
    id: "INT008",
    title: "Digital Marketing Intern",
    description: "Work with our digital marketing team to develop and implement online marketing campaigns. You'll gain experience in SEO, SEM, social media marketing, and content creation for digital platforms.",
    company: "Mena Digital Agency",
    location: "Dubai Knowledge Park, Dubai, UAE",
    start_date: "2025-07-01",
    end_date: "2025-12-31",
    application_deadline: "2025-05-31",
    is_paid: false,
    stipend_amount: 0,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Marketing, Digital Media, or related field",
      "Understanding of digital marketing channels",
      "Creative mindset and good writing skills"
    ],
    skills_required: ["SEO", "Social Media Marketing", "Content Creation", "Google Analytics"],
    industry: "Marketing & Advertising",
    department: "Digital Marketing",
    education_level: "Undergraduate",
    contact_email: "internships@menadigital.ae",
    website_url: "https://menadigital.ae",
    is_active: true,
    created_at: "2025-03-25",
    created_by: "user-505"
  },
  {
    id: "INT009",
    title: "Legal Intern",
    description: "Join our legal department to assist with contract reviews, legal research, and compliance matters. This internship offers valuable exposure to corporate and commercial law in the UAE context.",
    company: "Al Mubarak Legal Consultants",
    location: "Dubai International Financial Centre, Dubai, UAE",
    start_date: "2025-09-01",
    end_date: "2025-12-01",
    application_deadline: "2025-07-31",
    is_paid: true,
    stipend_amount: 4000,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Law",
      "Knowledge of UAE legal system",
      "Strong research and writing skills"
    ],
    skills_required: ["Legal Research", "Contract Review", "Legal Writing", "Compliance"],
    industry: "Legal Services",
    department: "Legal",
    education_level: "Graduate",
    contact_email: "careers@almubaraklegal.ae",
    website_url: "https://almubaraklegal.ae",
    is_active: false,
    created_at: "2025-03-30",
    created_by: "user-606"
  },
  {
    id: "INT010",
    title: "Environmental Research Intern",
    description: "Support our research team in conducting environmental studies, data collection, and sustainability initiatives. You'll be involved in field work, data analysis, and report preparation for environmental projects.",
    company: "Dubai Sustainability Center",
    location: "Al Quoz, Dubai, UAE",
    start_date: "2025-08-01",
    end_date: "2026-02-01",
    application_deadline: "2025-06-30",
    is_paid: true,
    stipend_amount: 3700,
    currency: "AED",
    requirements: [
      "Pursuing a degree in Environmental Science, Sustainability, or related field",
      "Passion for environmental conservation and sustainability",
      "Experience with data collection and analysis"
    ],
    skills_required: ["Environmental Monitoring", "Data Analysis", "Sustainability Practices", "Report Writing"],
    industry: "Environmental Services",
    department: "Research",
    education_level: "Undergraduate",
    contact_email: "info@dubaisustainability.ae",
    website_url: "https://dubaisustainability.ae",
    is_active: true,
    created_at: "2025-04-05",
    created_by: "user-707"
  }
];
