
export type UserRole = 
  | 'student' 
  | 'parent' 
  | 'educational_institution' 
  | 'training_center' 
  | 'recruiter' 
  | 'mentor' 
  | 'entrepreneur' 
  | 'retiree' 
  | 'government_representative' 
  | 'admin'
  | 'school_student'
  | 'national_service_participant'
  | 'university_student'
  | 'intern'
  | 'full_time_employee'
  | 'part_time_employee'
  | 'gig_worker'
  | 'jobseeker'
  | 'lifelong_learner'
  | 'retiree_advocate'
  | 'private_sector_recruiter'
  | 'assessment_center'
  | 'career_advisor'
  | 'platform_operator'
  | 'administrator'
  | 'super_user';
