// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltzrdfiqivmedupzcndj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0enJkZmlxaXZtZWR1cHpjbmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODQ0NzUsImV4cCI6MjA1ODE2MDQ3NX0.6_QGpupbOhluj4n7WGgZ1pcH5mBnpEM4hTaFxMjN86s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);